### ISSUE TITLE
How to generate SimGrasp Dataset?

### ISSUE THREAD

**Issue by CAN-Lee** [PKU-EPIC/HOTrack#8]
Hi @JYChen18 ,

Thanks for your amazing works. I learn a lot from it.

I would infer that the SimGrasp Dataset is made by first using GraspIt to generate grasp poses and then utilizing those  grasp poses to generate corresponding hands by MANO. Is it right?

So, would you mind providing any details in implementation of generation of SimGrasp Dataset? Like what developer tools or environments? 

Really appreciate it ！

Can

**Comment by JYChen18** [comment]
Hi Can, 

Thanks for your interest in our work.

At that time, to generate SimGrasp Dataset, we modify the code from [mano_grasp](https://github.com/ikalevatykh/mano_grasp), which can directly give you the MANO grasp pose. 

However, I recommend you try [DexGraspNet](https://github.com/PKU-EPIC/DexGraspNet/tree/mano) from our lab. Compared to GraspIt!, DexGraspNet is faster, more GPU-friendly, and most importantly, easier to use because it is in pure Python.

Jiayi

**Comment by CAN-Lee** [comment]
Hi @JYChen18 ,

Thanks for your reply. So kind of you. 

I think I know how to do and I will try DexGraspNet.

Can
